# Generated by Django 2.0.4 on 2018-05-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_auto_20180505_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='record_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
